//////////////////////////////////////////////////////////////////////////
/// \defgroup Radio Therapy Business Unit
///  Copyright, (c) Shanghai United Imaging Healthcare Inc., 2016
///  All rights reserved.
///
///  \author  ZHOU qiangqiang  mailto:qiangqiang.zhou@united-imaging.com
///
///  \file      rt_tps_database_object_helper_normgroup.cpp
///  \brief     This file was generated by CodeGenerater.exe 
///             From database version: 1.1.11
///
///  \version 1.0
///  \date    8/8/2017
///  \{
//////////////////////////////////////////////////////////////////////////

#include "StdAfx.h"
#include "rt_tps_database_object_helper.h"
#include "RtTpsDatabaseWrapper/rt_tps_database_interface_object_normgroup.h"
#include "boost/date_time/posix_time/time_parsers.hpp"
typedef boost::posix_time::ptime DATETIME_BOOST;
typedef boost::posix_time::time_duration TIME_BOOST;
typedef boost::gregorian::date DATE_BOOST;

RT_TPS_DATABASE_BEGIN_NAMESPACE;

bool RtDatabaseHelper::InsertUpdateDBFromObject(const RtNormgroup& src, bool bInsert)
{
    MYSQL_STMT* stmt = mysql_stmt_init(m_pMySql);
    if (!stmt)
    {
        TPS_LOG_DEV_ERROR<<"mysql_stmt_init(), out of memory";
        return false;
    }
    //32 parameters
    unsigned int field_num = 0;
    std::string sSql("");
    std::string sName("");
    if (!bInsert)
    {
        for (unsigned int i(0); i < NORMGROUP_FIELD_MAX; ++i)
        {
            if (!src.is_dirty(i)) continue;
            const char* file_name = ENUM2STRING_NORMGROUP_FIELD[i];
            if (sName.empty())
            {
                sName += std::string(file_name) + "=?";
            }
            else
            {
                sName += "," + std::string(file_name) + "=?";
            }
            ++field_num;
        }
        sSql = "UPDATE tmsnormgroup SET " + sName + " WHERE uid='" + src.get_uid() + "'";
    }
    else
    {
        std::string sValues("");
        for (unsigned int i(0); i < NORMGROUP_FIELD_MAX; ++i)
        {
            if (!src.is_dirty(i)) continue;
            const char* file_name = ENUM2STRING_NORMGROUP_FIELD[i];
            if (sName.empty())
            {
                sName += std::string(file_name);
                sValues += "?";
            }
            else
            {
                sName += "," + std::string(file_name);
                sValues += ",?";
            }
            ++field_num;
        }
        sSql = "INSERT INTO tmsnormgroup (" + sName + ") VALUES (" + sValues + ")";
    }
    if (mysql_stmt_prepare(stmt, sSql.c_str(), (unsigned long)sSql.size()))
    {
        TPS_LOG_DEV_ERROR<<" mysql_stmt_prepare(), failed "<< mysql_stmt_error(stmt);
        TPS_PRINTF_DEBUG("mysql_stmt_prepare(), failed %s\n", mysql_stmt_error(stmt));
        return false;
    }

    MYSQL_BIND* bind = new MYSQL_BIND[field_num];
    memset(bind, 0, sizeof(MYSQL_BIND)*field_num);
    my_bool     isnull = true;
    std::string	data_uid = "";
    std::string	data_planuid = "";
    std::string	data_normalpointpoiuid = "";
    std::string	data_tpsequipmentuid = "";
    std::string	data_machineuid = "";
    std::string	data_voiuid = "";
    std::string	data_optsettinguid = "";
    std::string	data_prescriptionuid = "";
    int			data_plantype = 0;
    std::string	data_name = "";
    std::string	data_planlabel = "";
    MYSQL_TIME	data_plandate;
    MYSQL_TIME	data_plantime;
    double		data_doseperfraction = 0.;
    int			data_fraction = 0;
    float		data_percentage = 0.f;
    int			data_rtplangeometry = 0;
    bool		data_isjoined = false;
    int			data_radiationtype = 0;
    MYSQL_TIME	data_estimatedtime;
    std::string	data_description = "";
    bool		data_isnorm2voi = false;
    bool		data_isnorm2voimeandose = false;
    float		data_normvoipercentagevolume = 0.f;
    int			data_tpsverno = 0;
    int			data_tmsverno = 0;
    bool		data_isgating = false;
    int			data_binmode = 0;
    double		data_beamonrangestart = 0.;
    double		data_beamonrangeend = 0.;
    MYSQL_TIME	data_updatetime;
    std::string	data_operatorid = "";

    unsigned int iCount = 0;
    for (unsigned int i(0); i < NORMGROUP_FIELD_MAX; ++i)
    {
        if (!src.is_dirty(i)) continue;
        if(!src.has_field(i))
        {
            bind[iCount].is_null = &isnull;
            ++iCount;
            continue;
        }
        switch (i)
        {
        case 0: 	//uid varchar
            {
                data_uid = src.get_uid();
                bind[iCount].buffer_type = MYSQL_TYPE_VAR_STRING;
                bind[iCount].buffer = (void*)data_uid.c_str();
                bind[iCount].buffer_length = (unsigned long)data_uid.size();
            }
            break;
        case 1: 	//planuid varchar
            {
                data_planuid = src.get_planuid();
                bind[iCount].buffer_type = MYSQL_TYPE_VAR_STRING;
                bind[iCount].buffer = (void*)data_planuid.c_str();
                bind[iCount].buffer_length = (unsigned long)data_planuid.size();
            }
            break;
        case 2: 	//normalpointpoiuid varchar
            {
                data_normalpointpoiuid = src.get_normalpointpoiuid();
                bind[iCount].buffer_type = MYSQL_TYPE_VAR_STRING;
                bind[iCount].buffer = (void*)data_normalpointpoiuid.c_str();
                bind[iCount].buffer_length = (unsigned long)data_normalpointpoiuid.size();
            }
            break;
        case 3: 	//tpsequipmentuid varchar
            {
                data_tpsequipmentuid = src.get_tpsequipmentuid();
                bind[iCount].buffer_type = MYSQL_TYPE_VAR_STRING;
                bind[iCount].buffer = (void*)data_tpsequipmentuid.c_str();
                bind[iCount].buffer_length = (unsigned long)data_tpsequipmentuid.size();
            }
            break;
        case 4: 	//machineuid varchar
            {
                data_machineuid = src.get_machineuid();
                bind[iCount].buffer_type = MYSQL_TYPE_VAR_STRING;
                bind[iCount].buffer = (void*)data_machineuid.c_str();
                bind[iCount].buffer_length = (unsigned long)data_machineuid.size();
            }
            break;
        case 5: 	//voiuid varchar
            {
                data_voiuid = src.get_voiuid();
                bind[iCount].buffer_type = MYSQL_TYPE_VAR_STRING;
                bind[iCount].buffer = (void*)data_voiuid.c_str();
                bind[iCount].buffer_length = (unsigned long)data_voiuid.size();
            }
            break;
        case 6: 	//optsettinguid varchar
            {
                data_optsettinguid = src.get_optsettinguid();
                bind[iCount].buffer_type = MYSQL_TYPE_VAR_STRING;
                bind[iCount].buffer = (void*)data_optsettinguid.c_str();
                bind[iCount].buffer_length = (unsigned long)data_optsettinguid.size();
            }
            break;
        case 7: 	//prescriptionuid varchar
            {
                data_prescriptionuid = src.get_prescriptionuid();
                bind[iCount].buffer_type = MYSQL_TYPE_VAR_STRING;
                bind[iCount].buffer = (void*)data_prescriptionuid.c_str();
                bind[iCount].buffer_length = (unsigned long)data_prescriptionuid.size();
            }
            break;
        case 8: 	//plantype int
            {
                data_plantype = src.get_plantype();
                bind[iCount].buffer_type = MYSQL_TYPE_LONG;
                bind[iCount].buffer = (void*)&data_plantype;
                bind[iCount].buffer_length = sizeof(int);
            }
            break;
        case 9: 	//name varchar
            {
                data_name = src.get_name();
                bind[iCount].buffer_type = MYSQL_TYPE_VAR_STRING;
                bind[iCount].buffer = (void*)data_name.c_str();
                bind[iCount].buffer_length = (unsigned long)data_name.size();
            }
            break;
        case 10: 	//planlabel varchar
            {
                data_planlabel = src.get_planlabel();
                bind[iCount].buffer_type = MYSQL_TYPE_VAR_STRING;
                bind[iCount].buffer = (void*)data_planlabel.c_str();
                bind[iCount].buffer_length = (unsigned long)data_planlabel.size();
            }
            break;
        case 11: 	//plandate date
            {
                ConvertDateTime2DB(src.get_plandate(), &data_plandate);
                bind[iCount].buffer_type = MYSQL_TYPE_DATE;
                bind[iCount].buffer = (void*)&data_plandate;
                if (src.get_plandate().is_not_a_date()) bind[iCount].is_null = &isnull;
            }
            break;
        case 12: 	//plantime time
            {
                ConvertDateTime2DB(src.get_plantime(), &data_plantime);
                bind[iCount].buffer_type = MYSQL_TYPE_TIME;
                bind[iCount].buffer = (void*)&data_plantime;
                if (src.get_plantime().is_not_a_date_time()) bind[iCount].is_null = &isnull;
            }
            break;
        case 13: 	//doseperfraction double
            {
                data_doseperfraction = src.get_doseperfraction();
                bind[iCount].buffer_type = MYSQL_TYPE_DOUBLE;
                bind[iCount].buffer = (void*)&data_doseperfraction;
                bind[iCount].buffer_length = sizeof(double);
            }
            break;
        case 14: 	//fraction int
            {
                data_fraction = src.get_fraction();
                bind[iCount].buffer_type = MYSQL_TYPE_LONG;
                bind[iCount].buffer = (void*)&data_fraction;
                bind[iCount].buffer_length = sizeof(int);
            }
            break;
        case 15: 	//percentage float
            {
                data_percentage = src.get_percentage();
                bind[iCount].buffer_type = MYSQL_TYPE_FLOAT;
                bind[iCount].buffer = (void*)&data_percentage;
                bind[iCount].buffer_length = sizeof(float);
            }
            break;
        case 16: 	//rtplangeometry int
            {
                data_rtplangeometry = src.get_rtplangeometry();
                bind[iCount].buffer_type = MYSQL_TYPE_LONG;
                bind[iCount].buffer = (void*)&data_rtplangeometry;
                bind[iCount].buffer_length = sizeof(int);
            }
            break;
        case 17: 	//isjoined tinyint
            {
                data_isjoined = src.get_isjoined();
                bind[iCount].buffer_type = MYSQL_TYPE_TINY;
                bind[iCount].buffer = (void*)&data_isjoined;
                bind[iCount].buffer_length = sizeof(bool);
            }
            break;
        case 18: 	//radiationtype int
            {
                data_radiationtype = src.get_radiationtype();
                bind[iCount].buffer_type = MYSQL_TYPE_LONG;
                bind[iCount].buffer = (void*)&data_radiationtype;
                bind[iCount].buffer_length = sizeof(int);
            }
            break;
        case 19: 	//estimatedtime time
            {
                ConvertDateTime2DB(src.get_estimatedtime(), &data_estimatedtime);
                bind[iCount].buffer_type = MYSQL_TYPE_TIME;
                bind[iCount].buffer = (void*)&data_estimatedtime;
                if (src.get_estimatedtime().is_not_a_date_time()) bind[iCount].is_null = &isnull;
            }
            break;
        case 20: 	//description varchar
            {
                data_description = src.get_description();
                bind[iCount].buffer_type = MYSQL_TYPE_VAR_STRING;
                bind[iCount].buffer = (void*)data_description.c_str();
                bind[iCount].buffer_length = (unsigned long)data_description.size();
            }
            break;
        case 21: 	//isnorm2voi tinyint
            {
                data_isnorm2voi = src.get_isnorm2voi();
                bind[iCount].buffer_type = MYSQL_TYPE_TINY;
                bind[iCount].buffer = (void*)&data_isnorm2voi;
                bind[iCount].buffer_length = sizeof(bool);
            }
            break;
        case 22: 	//isnorm2voimeandose tinyint
            {
                data_isnorm2voimeandose = src.get_isnorm2voimeandose();
                bind[iCount].buffer_type = MYSQL_TYPE_TINY;
                bind[iCount].buffer = (void*)&data_isnorm2voimeandose;
                bind[iCount].buffer_length = sizeof(bool);
            }
            break;
        case 23: 	//normvoipercentagevolume float
            {
                data_normvoipercentagevolume = src.get_normvoipercentagevolume();
                bind[iCount].buffer_type = MYSQL_TYPE_FLOAT;
                bind[iCount].buffer = (void*)&data_normvoipercentagevolume;
                bind[iCount].buffer_length = sizeof(float);
            }
            break;
        case 24: 	//tpsverno int
            {
                data_tpsverno = src.get_tpsverno();
                bind[iCount].buffer_type = MYSQL_TYPE_LONG;
                bind[iCount].buffer = (void*)&data_tpsverno;
                bind[iCount].buffer_length = sizeof(int);
            }
            break;
        case 25: 	//tmsverno int
            {
                data_tmsverno = src.get_tmsverno();
                bind[iCount].buffer_type = MYSQL_TYPE_LONG;
                bind[iCount].buffer = (void*)&data_tmsverno;
                bind[iCount].buffer_length = sizeof(int);
            }
            break;
        case 26: 	//isgating tinyint
            {
                data_isgating = src.get_isgating();
                bind[iCount].buffer_type = MYSQL_TYPE_TINY;
                bind[iCount].buffer = (void*)&data_isgating;
                bind[iCount].buffer_length = sizeof(bool);
            }
            break;
        case 27: 	//binmode int
            {
                data_binmode = src.get_binmode();
                bind[iCount].buffer_type = MYSQL_TYPE_LONG;
                bind[iCount].buffer = (void*)&data_binmode;
                bind[iCount].buffer_length = sizeof(int);
            }
            break;
        case 28: 	//beamonrangestart double
            {
                data_beamonrangestart = src.get_beamonrangestart();
                bind[iCount].buffer_type = MYSQL_TYPE_DOUBLE;
                bind[iCount].buffer = (void*)&data_beamonrangestart;
                bind[iCount].buffer_length = sizeof(double);
            }
            break;
        case 29: 	//beamonrangeend double
            {
                data_beamonrangeend = src.get_beamonrangeend();
                bind[iCount].buffer_type = MYSQL_TYPE_DOUBLE;
                bind[iCount].buffer = (void*)&data_beamonrangeend;
                bind[iCount].buffer_length = sizeof(double);
            }
            break;
        case 30: 	//updatetime timestamp
            {
                ConvertDateTime2DB(src.get_updatetime(), &data_updatetime);
                bind[iCount].buffer_type = MYSQL_TYPE_TIMESTAMP;
                bind[iCount].buffer = (void*)&data_updatetime;
                if (src.get_updatetime().is_not_a_date_time()) bind[iCount].is_null = &isnull;
            }
            break;
        case 31: 	//operatorid varchar
            {
                data_operatorid = src.get_operatorid();
                bind[iCount].buffer_type = MYSQL_TYPE_VAR_STRING;
                bind[iCount].buffer = (void*)data_operatorid.c_str();
                bind[iCount].buffer_length = (unsigned long)data_operatorid.size();
            }
            break;
        default:
            break;
        }

        ++iCount;
    }
    if (mysql_stmt_bind_param(stmt, bind))
    {
        TPS_LOG_DEV_ERROR<<" mysql_stmt_bind_param(), failed "<< mysql_stmt_error(stmt);
        DEL_ARRAY(bind);
        return false;
    }
    if (mysql_stmt_execute(stmt))
    {
        TPS_LOG_DEV_ERROR<<" mysql_stmt_execute(), failed "<< mysql_stmt_error(stmt);
        TPS_PRINTF_DEBUG("mysql_stmt_execute(), failed %s\n", mysql_stmt_error(stmt));
        DEL_ARRAY(bind);
        return false;
    }
    if (mysql_stmt_close(stmt))
    {
        TPS_LOG_DEV_ERROR<<" failed while closing the statement "<< mysql_stmt_error(stmt);
        DEL_ARRAY(bind);
        return false;
    }
	DEL_ARRAY(bind);
	RtDatabaseObject* rtDatabaseObject = const_cast<RtNormgroup*>(&src);
	rtDatabaseObject->setdirty_all_fields(false);
    return true;
}

bool RtDatabaseHelper::FetchDataFromDB(const std::string& sSql, std::vector<RtNormgroup*>& vList)
{
    MYSQL_STMT* stmt = mysql_stmt_init(m_pMySql);
    if (!stmt)
    {
        TPS_LOG_DEV_ERROR<<"mysql_stmt_init(), out of memory";
        return false;
    }

    MYSQL_RES  *prepare_meta_result = nullptr;
    //tmsnormgroup    32 parameters
    const int field_num = NORMGROUP_FIELD_MAX;
    unsigned long MAX_LENGTH[field_num] = {0};
    MAX_LENGTH[0] = 64;
    MAX_LENGTH[1] = 64;
    MAX_LENGTH[2] = 64;
    MAX_LENGTH[3] = 64;
    MAX_LENGTH[4] = 64;
    MAX_LENGTH[5] = 64;
    MAX_LENGTH[6] = 64;
    MAX_LENGTH[7] = 64;
    MAX_LENGTH[8] = 0;
    MAX_LENGTH[9] = 256;
    MAX_LENGTH[10] = 64;
    MAX_LENGTH[11] = 0;
    MAX_LENGTH[12] = 0;
    MAX_LENGTH[13] = 0;
    MAX_LENGTH[14] = 0;
    MAX_LENGTH[15] = 0;
    MAX_LENGTH[16] = 0;
    MAX_LENGTH[17] = 0;
    MAX_LENGTH[18] = 0;
    MAX_LENGTH[19] = 0;
    MAX_LENGTH[20] = 1024;
    MAX_LENGTH[21] = 0;
    MAX_LENGTH[22] = 0;
    MAX_LENGTH[23] = 0;
    MAX_LENGTH[24] = 0;
    MAX_LENGTH[25] = 0;
    MAX_LENGTH[26] = 0;
    MAX_LENGTH[27] = 0;
    MAX_LENGTH[28] = 0;
    MAX_LENGTH[29] = 0;
    MAX_LENGTH[30] = 0;
    MAX_LENGTH[31] = 64;

    //std::string	data_uid
    //std::string	data_planuid
    //std::string	data_normalpointpoiuid
    //std::string	data_tpsequipmentuid
    //std::string	data_machineuid
    //std::string	data_voiuid
    //std::string	data_optsettinguid
    //std::string	data_prescriptionuid
    int	data_plantype = 0;
    //std::string	data_name
    //std::string	data_planlabel
    MYSQL_TIME	data_plandate;
    MYSQL_TIME	data_plantime;
    double	data_doseperfraction = 0.;
    int	data_fraction = 0;
    float	data_percentage = 0.f;
    int	data_rtplangeometry = 0;
    bool	data_isjoined = false;
    int	data_radiationtype = 0;
    MYSQL_TIME	data_estimatedtime;
    //std::string	data_description
    bool	data_isnorm2voi = false;
    bool	data_isnorm2voimeandose = false;
    float	data_normvoipercentagevolume = 0.f;
    int	data_tpsverno = 0;
    int	data_tmsverno = 0;
    bool	data_isgating = false;
    int	data_binmode = 0;
    double	data_beamonrangestart = 0.;
    double	data_beamonrangeend = 0.;
    MYSQL_TIME	data_updatetime;
    //std::string	data_operatorid

    if (mysql_stmt_prepare(stmt, sSql.c_str(), (unsigned long)strlen(sSql.c_str())))
    {
        TPS_LOG_DEV_ERROR<<" mysql_stmt_prepare(), SELECT failed."<<mysql_stmt_error(stmt);
        return false;
    }

    //Fetch result set meta information
    prepare_meta_result = mysql_stmt_result_metadata(stmt);
    if (!prepare_meta_result) 
    {
        TPS_LOG_DEV_ERROR<<" mysql_stmt_result_metadata(), returned no meta information "<<mysql_stmt_error(stmt);
        return false;
    }

    // Get total columns in the query and validate column count
    const unsigned int column_count= mysql_num_fields(prepare_meta_result);
    if (column_count != field_num)
    {
        TPS_LOG_DEV_ERROR<<"invalid column count returned by MySQL";
        return false;
    }

    MYSQL_BIND* bind = new MYSQL_BIND[column_count];
    memset(bind, 0, sizeof(MYSQL_BIND)*column_count);
    unsigned long* length = new unsigned long[column_count];
    memset(length, 0, sizeof(unsigned long) * column_count);
    my_bool* is_null = new my_bool[column_count];
    memset(is_null, 0, sizeof(my_bool) * column_count);
    //Execute the SELECT query
    char* data_string[field_num];
    for (int i=0; i<field_num; ++i)
    {
        const unsigned long ulSize = MAX_LENGTH[i] + 1;// + 1 for string's \0 
        data_string[i] = new char[ulSize];
        memset(data_string[i], 0, ulSize*sizeof(char));
    }
    if (mysql_stmt_execute(stmt))
    {
        TPS_LOG_DEV_ERROR<<" mysql_stmt_execute(), failed"<<mysql_stmt_error(stmt);
        for (int i=0; i<field_num; ++i) DEL_ARRAY(data_string[i]);
        DEL_ARRAY(bind);
        DEL_ARRAY(length);
        DEL_ARRAY(is_null);
        return false;
    }

    for (unsigned int i(0); i<column_count; ++i)
    {
        bind[i].is_null= &is_null[i];
        bind[i].length= &length[i];
        switch (i)
        {
        case 8: 	//plantype int
            bind[i].buffer_type= MYSQL_TYPE_LONG;
            bind[i].buffer= (char *)&data_plantype;
            break;
        case 11: 	//plandate date
            bind[i].buffer_type= MYSQL_TYPE_DATE;
            bind[i].buffer= (char *)&data_plandate;
            break;
        case 12: 	//plantime time
            bind[i].buffer_type= MYSQL_TYPE_TIME;
            bind[i].buffer= (char *)&data_plantime;
            break;
        case 13: 	//doseperfraction double
            bind[i].buffer_type= MYSQL_TYPE_DOUBLE;
            bind[i].buffer= (char *)&data_doseperfraction;
            break;
        case 14: 	//fraction int
            bind[i].buffer_type= MYSQL_TYPE_LONG;
            bind[i].buffer= (char *)&data_fraction;
            break;
        case 15: 	//percentage float
            bind[i].buffer_type= MYSQL_TYPE_FLOAT;
            bind[i].buffer= (char *)&data_percentage;
            break;
        case 16: 	//rtplangeometry int
            bind[i].buffer_type= MYSQL_TYPE_LONG;
            bind[i].buffer= (char *)&data_rtplangeometry;
            break;
        case 17: 	//isjoined tinyint
            bind[i].buffer_type= MYSQL_TYPE_TINY;
            bind[i].buffer= (char *)&data_isjoined;
            break;
        case 18: 	//radiationtype int
            bind[i].buffer_type= MYSQL_TYPE_LONG;
            bind[i].buffer= (char *)&data_radiationtype;
            break;
        case 19: 	//estimatedtime time
            bind[i].buffer_type= MYSQL_TYPE_TIME;
            bind[i].buffer= (char *)&data_estimatedtime;
            break;
        case 21: 	//isnorm2voi tinyint
            bind[i].buffer_type= MYSQL_TYPE_TINY;
            bind[i].buffer= (char *)&data_isnorm2voi;
            break;
        case 22: 	//isnorm2voimeandose tinyint
            bind[i].buffer_type= MYSQL_TYPE_TINY;
            bind[i].buffer= (char *)&data_isnorm2voimeandose;
            break;
        case 23: 	//normvoipercentagevolume float
            bind[i].buffer_type= MYSQL_TYPE_FLOAT;
            bind[i].buffer= (char *)&data_normvoipercentagevolume;
            break;
        case 24: 	//tpsverno int
            bind[i].buffer_type= MYSQL_TYPE_LONG;
            bind[i].buffer= (char *)&data_tpsverno;
            break;
        case 25: 	//tmsverno int
            bind[i].buffer_type= MYSQL_TYPE_LONG;
            bind[i].buffer= (char *)&data_tmsverno;
            break;
        case 26: 	//isgating tinyint
            bind[i].buffer_type= MYSQL_TYPE_TINY;
            bind[i].buffer= (char *)&data_isgating;
            break;
        case 27: 	//binmode int
            bind[i].buffer_type= MYSQL_TYPE_LONG;
            bind[i].buffer= (char *)&data_binmode;
            break;
        case 28: 	//beamonrangestart double
            bind[i].buffer_type= MYSQL_TYPE_DOUBLE;
            bind[i].buffer= (char *)&data_beamonrangestart;
            break;
        case 29: 	//beamonrangeend double
            bind[i].buffer_type= MYSQL_TYPE_DOUBLE;
            bind[i].buffer= (char *)&data_beamonrangeend;
            break;
        case 30: 	//updatetime timestamp
            bind[i].buffer_type= MYSQL_TYPE_TIMESTAMP;
            bind[i].buffer= (char *)&data_updatetime;
            break;
        default:
            bind[i].buffer_type= MYSQL_TYPE_STRING;
            bind[i].buffer= (char *)data_string[i];
            bind[i].buffer_length= MAX_LENGTH[i];
            break;
        }
    }

    // Bind the result buffers
    if (mysql_stmt_bind_result(stmt, bind))
    {
        TPS_LOG_DEV_ERROR<<" mysql_stmt_bind_result() failed "<<mysql_stmt_error(stmt);
        for (int i=0; i<field_num; ++i) DEL_ARRAY(data_string[i]);
        DEL_ARRAY(bind);
        DEL_ARRAY(length);
        DEL_ARRAY(is_null);
        return false;
    }

    //Now buffer all results to client
    if (mysql_stmt_store_result(stmt))
    {
        TPS_LOG_DEV_ERROR<<" mysql_stmt_store_result() failed "<<mysql_stmt_error(stmt);
        for (int i=0; i<field_num; ++i) DEL_ARRAY(data_string[i]);
        DEL_ARRAY(bind);
        DEL_ARRAY(length);
        DEL_ARRAY(is_null);
        return false;
    }

    // Fetch all rows 
    int ret(1);
    RtNormgroup* pDis = nullptr;
    while(true)
    {
        ret = mysql_stmt_fetch(stmt);
        if (ret!=0 && ret!=MYSQL_DATA_TRUNCATED) break;
        pDis = new RtNormgroup();
        for (unsigned int i(0); i<column_count; ++i)
        {
            if (is_null[i]) continue;
            switch (i)
            {
            case 0: 	//uid varchar
                pDis->set_uid((char *)bind[i].buffer);
                break;
            case 1: 	//planuid varchar
                pDis->set_planuid((char *)bind[i].buffer);
                break;
            case 2: 	//normalpointpoiuid varchar
                pDis->set_normalpointpoiuid((char *)bind[i].buffer);
                break;
            case 3: 	//tpsequipmentuid varchar
                pDis->set_tpsequipmentuid((char *)bind[i].buffer);
                break;
            case 4: 	//machineuid varchar
                pDis->set_machineuid((char *)bind[i].buffer);
                break;
            case 5: 	//voiuid varchar
                pDis->set_voiuid((char *)bind[i].buffer);
                break;
            case 6: 	//optsettinguid varchar
                pDis->set_optsettinguid((char *)bind[i].buffer);
                break;
            case 7: 	//prescriptionuid varchar
                pDis->set_prescriptionuid((char *)bind[i].buffer);
                break;
            case 8: 	//plantype int
                pDis->set_plantype(data_plantype);
                break;
            case 9: 	//name varchar
                pDis->set_name((char *)bind[i].buffer);
                break;
            case 10: 	//planlabel varchar
                pDis->set_planlabel((char *)bind[i].buffer);
                break;
            case 11: 	//plandate date
                {
                    DATE_BOOST plandate;
                    ConvertDateTime2Boost(data_plandate, &plandate);
                    pDis->set_plandate(plandate);
                }
                break;
            case 12: 	//plantime time
                {
                    TIME_BOOST plantime;
                    ConvertDateTime2Boost(data_plantime, &plantime);
                    pDis->set_plantime(plantime);
                }
                break;
            case 13: 	//doseperfraction double
                pDis->set_doseperfraction(data_doseperfraction);
                break;
            case 14: 	//fraction int
                pDis->set_fraction(data_fraction);
                break;
            case 15: 	//percentage float
                pDis->set_percentage(data_percentage);
                break;
            case 16: 	//rtplangeometry int
                pDis->set_rtplangeometry(data_rtplangeometry);
                break;
            case 17: 	//isjoined tinyint
                pDis->set_isjoined(data_isjoined);
                break;
            case 18: 	//radiationtype int
                pDis->set_radiationtype(data_radiationtype);
                break;
            case 19: 	//estimatedtime time
                {
                    TIME_BOOST estimatedtime;
                    ConvertDateTime2Boost(data_estimatedtime, &estimatedtime);
                    pDis->set_estimatedtime(estimatedtime);
                }
                break;
            case 20: 	//description varchar
                pDis->set_description((char *)bind[i].buffer);
                break;
            case 21: 	//isnorm2voi tinyint
                pDis->set_isnorm2voi(data_isnorm2voi);
                break;
            case 22: 	//isnorm2voimeandose tinyint
                pDis->set_isnorm2voimeandose(data_isnorm2voimeandose);
                break;
            case 23: 	//normvoipercentagevolume float
                pDis->set_normvoipercentagevolume(data_normvoipercentagevolume);
                break;
            case 24: 	//tpsverno int
                pDis->set_tpsverno(data_tpsverno);
                break;
            case 25: 	//tmsverno int
                pDis->set_tmsverno(data_tmsverno);
                break;
            case 26: 	//isgating tinyint
                pDis->set_isgating(data_isgating);
                break;
            case 27: 	//binmode int
                pDis->set_binmode(data_binmode);
                break;
            case 28: 	//beamonrangestart double
                pDis->set_beamonrangestart(data_beamonrangestart);
                break;
            case 29: 	//beamonrangeend double
                pDis->set_beamonrangeend(data_beamonrangeend);
                break;
            case 30: 	//updatetime timestamp
                {
                    DATETIME_BOOST updatetime;
                    ConvertDateTime2Boost(data_updatetime, &updatetime);
                    pDis->set_updatetime(updatetime);
                }
                break;
            case 31: 	//operatorid varchar
                pDis->set_operatorid((char *)bind[i].buffer);
                break;
            default:
                break;
            }
        }
        pDis->setdirty_all_fields(false);
        vList.push_back(pDis);
    }
    for (int i=0; i<field_num; ++i) DEL_ARRAY(data_string[i]);
    DEL_ARRAY(bind);
    DEL_ARRAY(length);
    DEL_ARRAY(is_null);

    // Free the prepared result metadata
    mysql_free_result(prepare_meta_result);

    // Close the statement
    if (mysql_stmt_close(stmt))
    {
        TPS_LOG_DEV_ERROR<<" failed while closing the statement " << mysql_stmt_error(stmt);
        return false;
    }

    return true;
}

RT_TPS_DATABASE_END_NAMESPACE