// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rt_tps_proto_template.proto

#ifndef PROTOBUF_rt_5ftps_5fproto_5ftemplate_2eproto__INCLUDED
#define PROTOBUF_rt_5ftps_5fproto_5ftemplate_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace tps {
namespace proto {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_rt_5ftps_5fproto_5ftemplate_2eproto();
void protobuf_AssignDesc_rt_5ftps_5fproto_5ftemplate_2eproto();
void protobuf_ShutdownFile_rt_5ftps_5fproto_5ftemplate_2eproto();

class RtTpsProtoTemplate;
class RtTpsProtoRepeatedTemplates;

// ===================================================================

class RtTpsProtoTemplate : public ::google::protobuf::Message {
 public:
  RtTpsProtoTemplate();
  virtual ~RtTpsProtoTemplate();
  
  RtTpsProtoTemplate(const RtTpsProtoTemplate& from);
  
  inline RtTpsProtoTemplate& operator=(const RtTpsProtoTemplate& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const RtTpsProtoTemplate& default_instance();
  
  void Swap(RtTpsProtoTemplate* other);
  
  // implements Message ----------------------------------------------
  
  RtTpsProtoTemplate* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RtTpsProtoTemplate& from);
  void MergeFrom(const RtTpsProtoTemplate& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional string uid = 1;
  inline bool has_uid() const;
  inline void clear_uid();
  static const int kUidFieldNumber = 1;
  inline const ::std::string& uid() const;
  inline void set_uid(const ::std::string& value);
  inline void set_uid(const char* value);
  inline void set_uid(const char* value, size_t size);
  inline ::std::string* mutable_uid();
  inline ::std::string* release_uid();
  
  // optional string name = 2;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 2;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  
  // optional string value = 3;
  inline bool has_value() const;
  inline void clear_value();
  static const int kValueFieldNumber = 3;
  inline const ::std::string& value() const;
  inline void set_value(const ::std::string& value);
  inline void set_value(const char* value);
  inline void set_value(const char* value, size_t size);
  inline ::std::string* mutable_value();
  inline ::std::string* release_value();
  
  // @@protoc_insertion_point(class_scope:tps.proto.RtTpsProtoTemplate)
 private:
  inline void set_has_uid();
  inline void clear_has_uid();
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_value();
  inline void clear_has_value();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* uid_;
  ::std::string* name_;
  ::std::string* value_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void  protobuf_AddDesc_rt_5ftps_5fproto_5ftemplate_2eproto();
  friend void protobuf_AssignDesc_rt_5ftps_5fproto_5ftemplate_2eproto();
  friend void protobuf_ShutdownFile_rt_5ftps_5fproto_5ftemplate_2eproto();
  
  void InitAsDefaultInstance();
  static RtTpsProtoTemplate* default_instance_;
};
// -------------------------------------------------------------------

class RtTpsProtoRepeatedTemplates : public ::google::protobuf::Message {
 public:
  RtTpsProtoRepeatedTemplates();
  virtual ~RtTpsProtoRepeatedTemplates();
  
  RtTpsProtoRepeatedTemplates(const RtTpsProtoRepeatedTemplates& from);
  
  inline RtTpsProtoRepeatedTemplates& operator=(const RtTpsProtoRepeatedTemplates& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const RtTpsProtoRepeatedTemplates& default_instance();
  
  void Swap(RtTpsProtoRepeatedTemplates* other);
  
  // implements Message ----------------------------------------------
  
  RtTpsProtoRepeatedTemplates* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RtTpsProtoRepeatedTemplates& from);
  void MergeFrom(const RtTpsProtoRepeatedTemplates& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // repeated .tps.proto.RtTpsProtoTemplate templates = 1;
  inline int templates_size() const;
  inline void clear_templates();
  static const int kTemplatesFieldNumber = 1;
  inline const ::tps::proto::RtTpsProtoTemplate& templates(int index) const;
  inline ::tps::proto::RtTpsProtoTemplate* mutable_templates(int index);
  inline ::tps::proto::RtTpsProtoTemplate* add_templates();
  inline const ::google::protobuf::RepeatedPtrField< ::tps::proto::RtTpsProtoTemplate >&
      templates() const;
  inline ::google::protobuf::RepeatedPtrField< ::tps::proto::RtTpsProtoTemplate >*
      mutable_templates();
  
  // @@protoc_insertion_point(class_scope:tps.proto.RtTpsProtoRepeatedTemplates)
 private:
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedPtrField< ::tps::proto::RtTpsProtoTemplate > templates_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_rt_5ftps_5fproto_5ftemplate_2eproto();
  friend void protobuf_AssignDesc_rt_5ftps_5fproto_5ftemplate_2eproto();
  friend void protobuf_ShutdownFile_rt_5ftps_5fproto_5ftemplate_2eproto();
  
  void InitAsDefaultInstance();
  static RtTpsProtoRepeatedTemplates* default_instance_;
};
// ===================================================================


// ===================================================================

// RtTpsProtoTemplate

// optional string uid = 1;
inline bool RtTpsProtoTemplate::has_uid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RtTpsProtoTemplate::set_has_uid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RtTpsProtoTemplate::clear_has_uid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RtTpsProtoTemplate::clear_uid() {
  if (uid_ != &::google::protobuf::internal::kEmptyString) {
    uid_->clear();
  }
  clear_has_uid();
}
inline const ::std::string& RtTpsProtoTemplate::uid() const {
  return *uid_;
}
inline void RtTpsProtoTemplate::set_uid(const ::std::string& value) {
  set_has_uid();
  if (uid_ == &::google::protobuf::internal::kEmptyString) {
    uid_ = new ::std::string;
  }
  uid_->assign(value);
}
inline void RtTpsProtoTemplate::set_uid(const char* value) {
  set_has_uid();
  if (uid_ == &::google::protobuf::internal::kEmptyString) {
    uid_ = new ::std::string;
  }
  uid_->assign(value);
}
inline void RtTpsProtoTemplate::set_uid(const char* value, size_t size) {
  set_has_uid();
  if (uid_ == &::google::protobuf::internal::kEmptyString) {
    uid_ = new ::std::string;
  }
  uid_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* RtTpsProtoTemplate::mutable_uid() {
  set_has_uid();
  if (uid_ == &::google::protobuf::internal::kEmptyString) {
    uid_ = new ::std::string;
  }
  return uid_;
}
inline ::std::string* RtTpsProtoTemplate::release_uid() {
  clear_has_uid();
  if (uid_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = uid_;
    uid_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// optional string name = 2;
inline bool RtTpsProtoTemplate::has_name() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RtTpsProtoTemplate::set_has_name() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RtTpsProtoTemplate::clear_has_name() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RtTpsProtoTemplate::clear_name() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& RtTpsProtoTemplate::name() const {
  return *name_;
}
inline void RtTpsProtoTemplate::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void RtTpsProtoTemplate::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void RtTpsProtoTemplate::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* RtTpsProtoTemplate::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  return name_;
}
inline ::std::string* RtTpsProtoTemplate::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// optional string value = 3;
inline bool RtTpsProtoTemplate::has_value() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void RtTpsProtoTemplate::set_has_value() {
  _has_bits_[0] |= 0x00000004u;
}
inline void RtTpsProtoTemplate::clear_has_value() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void RtTpsProtoTemplate::clear_value() {
  if (value_ != &::google::protobuf::internal::kEmptyString) {
    value_->clear();
  }
  clear_has_value();
}
inline const ::std::string& RtTpsProtoTemplate::value() const {
  return *value_;
}
inline void RtTpsProtoTemplate::set_value(const ::std::string& value) {
  set_has_value();
  if (value_ == &::google::protobuf::internal::kEmptyString) {
    value_ = new ::std::string;
  }
  value_->assign(value);
}
inline void RtTpsProtoTemplate::set_value(const char* value) {
  set_has_value();
  if (value_ == &::google::protobuf::internal::kEmptyString) {
    value_ = new ::std::string;
  }
  value_->assign(value);
}
inline void RtTpsProtoTemplate::set_value(const char* value, size_t size) {
  set_has_value();
  if (value_ == &::google::protobuf::internal::kEmptyString) {
    value_ = new ::std::string;
  }
  value_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* RtTpsProtoTemplate::mutable_value() {
  set_has_value();
  if (value_ == &::google::protobuf::internal::kEmptyString) {
    value_ = new ::std::string;
  }
  return value_;
}
inline ::std::string* RtTpsProtoTemplate::release_value() {
  clear_has_value();
  if (value_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = value_;
    value_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// -------------------------------------------------------------------

// RtTpsProtoRepeatedTemplates

// repeated .tps.proto.RtTpsProtoTemplate templates = 1;
inline int RtTpsProtoRepeatedTemplates::templates_size() const {
  return templates_.size();
}
inline void RtTpsProtoRepeatedTemplates::clear_templates() {
  templates_.Clear();
}
inline const ::tps::proto::RtTpsProtoTemplate& RtTpsProtoRepeatedTemplates::templates(int index) const {
  return templates_.Get(index);
}
inline ::tps::proto::RtTpsProtoTemplate* RtTpsProtoRepeatedTemplates::mutable_templates(int index) {
  return templates_.Mutable(index);
}
inline ::tps::proto::RtTpsProtoTemplate* RtTpsProtoRepeatedTemplates::add_templates() {
  return templates_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::tps::proto::RtTpsProtoTemplate >&
RtTpsProtoRepeatedTemplates::templates() const {
  return templates_;
}
inline ::google::protobuf::RepeatedPtrField< ::tps::proto::RtTpsProtoTemplate >*
RtTpsProtoRepeatedTemplates::mutable_templates() {
  return &templates_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace tps

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_rt_5ftps_5fproto_5ftemplate_2eproto__INCLUDED
