//////////////////////////////////////////////////////////////////////////
/// \defgroup TPS of Radio Therapy Business Unit
///  Copyright, (c) Shanghai United Imaging Healthcare Inc., 2013
///  All rights reserved.
///
///  \author  ZHOU Qiangqiang qiangqiang.zhou@united-imaging.com
///
///  \file    tps_fw_commandids.h
///  \brief   TPS Command IDs
///
///  \version 1.0
///  \date    Jan. 3, 2014
///  \{
//////////////////////////////////////////////////////////////////////////
#ifndef  TPS_FW_COMMANDIDS_H_
#define  TPS_FW_COMMANDIDS_H_

//TPS Command: 130001~132000
//TPS Event: 1300001~1320000
// FE --> BE
enum TpsFE2BECommand{
    NULLCOMMAND                                         = -1,

    // For Common 130001~130200
    //LOAD_COMMON                                         = 130001,
    LOAD_PATIENT                                        = 130002,
    MPR_PAGE_TURN                                       = 130003,
    MPR_PAGE_PAN                                        = 130004,
    MPR_PAGE_ZOOM                                       = 130005,
    MPR_PAGE_WINDOWING                                  = 130006,
    RETRIEVE_VOI_LIST                                   = 130007,
    ACTION_CHANGED                                      = 130008,
    //MPR_CURSOR_POINTER                                  = 130009,
    REDO_UNDO_CONTOURING                                = 130010,
    MOUSE_POSITION_CHANGE                               = 130011,
    MOVIE                                               = 130012,
    PREVIEW_PAGE_TURN                                   = 130013,
    LOAD_VOI_TEMPLATE                                   = 130014,
    LOAD_SERIES_NEW                                     = 130015,
    LOAD_VOI_NEW                                        = 130016,
    LOAD_POI_NEW                                        = 130017,
    LOAD_BEAM_TEMPLATE                                  = 130018,
    LOAD_MACHINE_CONFIG_NEW                             = 130019, //The first command of TPS
    CALCULATE_DOSE_NEW                                  = 130020,
    LOAD_ACCESSORY                                      = 130021,
    CLEAR_DOSEGRID                                      = 130022,
    LOAD_OPTIMIZER_TEMPLATE                             = 130023,
    LOAD_OPTIMIZER_TEMPLATELIST                         = 130024,
    UPDATE_BEAM_VISIBILITY                              = 130025,
    LOAD_SYSTEM_CT2DENSITY_TABLE                        = 130026,
    LOAD_DOSELINETEMPLATE                               = 130027,
    REFRESH_DOSELINE_PARAMS                             = 130028,
    SET_SERIES_GROUP                                    = 130029,
    SET_MAIN_PHASE                                      = 130030,
    REMOVE_REGISTRATION_RELATIONSHIP                    = 130031,
    SWITCH_SERIES                                       = 130032,
    SHOW_FUSION_IMAGE                                   = 130033,
    PLAN_GOAL_SELECTION_CHANGED                         = 130034,
    CREATE_DOSELINETEMPLATE                             = 130035,
    DELETE_DOSELINETEMPLATE                             = 130036,
    CHANGE_PSEUDO_COLOR                                 = 130037,
    UPDATE_FUSION_INFO_COMMON                           = 130038,
    EDIT_CHESS                                          = 130039,
    UPDATE_CROSSHAIR                                    = 130040,
    CHANGE_BEV_EDIT_TARGET                              = 130041,
    TEST_CAN_SWITCH_TO_TPS                              = 130042,
    SHADEDSURFACE_ROTATE                                = 130043,
    SHADEDSURFACE_ZOOM                                  = 130044,
    RECOMPOSE_DOSE                                      = 130045,
    UPDATEDRRSETTING                                    = 130046,
	PLAY_SERIES											= 130047,

    //for Contouring 130201~130400
    CREATE_VIEW_MODULE_CONTOURING                       = 130201,
    ADD_VOI_AUTO                                        = 130202,
    ADD_VOI                                             = 130203,
    SMART_CONTOUR                                       = 130204,
    ADD_VOIS_FROM_TEMPLATE                              = 130205,
    UPDATE_VOI_DISPLAYATTRIBUTES                        = 130206,
    DELETE_VOI                                      = 130207,
    NUDGE                                               = 130208,
    SET_FUSION_IMAGE                                    = 130209,
    UPDATE_LIMIT_REGION                                 = 130210,
    SHOW_LIMIT_REGION                                   = 130211,
    UPDATE_FUSION_INFO                                  = 130212,
    UPDATE_VOI_DETAIL                                   = 130213,
    HIDE_LIMIT_REGION                                   = 130214,
    MANUAL_FUSION                                       = 130215,
    SEMI_AUTO_CONTOUR                                   = 130216,
    CUT_CONTOURS                                        = 130217,
    SELECT_CONTOURS_SLICES                              = 130218,
    GET_CURRENT_SLICE                                   = 130219,
    GET_DENSITY                                         = 130220,
    REGIN_GROWING                                       = 130221,
    SMOOTH_VOI                                          = 130222,
    REMOVE_SMALL_CONTOURS                               = 130223,
    ADD_VOI_ADVANCED                                    = 130224,
    MOVE_VOI                                            = 130225,
    APPROVE_VOI                                         = 130226,
    ADD_LANDMARK_POINT                                  = 130227,
    DISPLAY_FUSION_REGION                               = 130228,
    EDIT_FUSION_REGION                                  = 130229,
   // FLIP_IMAGE                                          = 130230,
  //  AUTO_REMOVE_TABLE                                   = 130231,
    MANUAL_REMOVE_TABLE                                 = 130232,
    DELETE_IMAGE_CONTOURING                             = 130233,
    LOAD_IMAGE4D_CONTOURING                             = 130234,
    PLAY_IMAGE4D_CONTOURING                             = 130235,
    CROSSHAIR_MODE_CONTOURING                           = 130236,
    APPROVE_FUSION                                      = 130237,
    VOI_MANSET_DENSITY                                  = 130238,
    SAVE_VOI_TEMPLATE                                   = 130239,
    ADD_POI_FROM_BEAMISOCENTER                          = 130240,
    EDIT_LANDMARK_POINT                                 = 130241,
    SAVE_OPTIMIZER_TEMPLATE                             = 130242,
    POI_CREATE_CONTOURING                               = 130243,
    POI_EDIT_2D_CONTOURING                              = 130244,
    POI_UPDATE_ATTRIBUTE_CONTOURING                     = 130245,
    POI_JUMP_TO_CONTOURING                              = 130246,
    CHANGE_CT2DENSITYTABLE                              = 130247,
    REMOVE_VOI_PREVIEW_WINDOWS                          = 130248,
    SET_RULER_VISIBILITY                                = 130249,
    SET_CORNERTEXT_VISIBILITY                           = 130250,
    SET_DRR_VISIBILITY                                  = 130251,
    SET_MLC_VISIBILITY                                  = 130252,
    RESET_MPR                                           = 130253,
    VOI_JUMP_TO                                         = 130254,

    //for Planning 130401~130600
    CREATE_VIEW_MODULE_PLANNING                         = 130401,
    ADD_PLAN                                            = 130402,
    CREATE_NORMGROUP                                    = 130403,
    CREATE_BEAM                                         = 130404,
    EDIT_PLAN                                           = 130405,
    EDIT_NORMGROUP                                      = 130406,
    EDIT_BEAM                                           = 130407,
    EDIT_BEAM_ONTHEFLY                                  = 130408,
    //BEAM_OUTLINE_COMMAND                                = 130410,
    PLANNING_DELETE                                     = 130411,
    MLC_DRAG                                            = 130412,
    SWITCH_SEGMENT                                      = 130414,
    UPDATE_GRIDSIZE                                     = 130415,
    UPDATE_GRIDBOUNDARY                                 = 130416,
    START_OPT                                           = 130417,
    SUSPEND_OPT                                         = 130418,
    RESUME_OPT                                          = 130419,
    ABORT_OPT                                           = 130420,
    DISPLAY_COMBINED_SEGMENT                            = 130421,
    UPDATE_VR_DISPLAY                                   = 130422,
    DRR_WINDOWING                                       = 130423,
    BEV_PAN                                             = 130424,
    BEV_ZOOM                                            = 130425,
    BEV_CEV                                             = 130426,
    DRR_FLUENCEMAP_SWITCH                               = 130431,
    MLC_SMARTCONTOUR                                    = 130432,
    MLC_RECTANGLE                                       = 130433,
    MLC_CIRCLE                                          = 130434,
    MLC_NUDGE                                           = 130435,
    MLC_FLIP                                            = 130436,
    HOT_SPOTS                                           = 130437,
    COLD_SPOTS                                          = 130438,
    REFRSH_DVH                                          = 130439,
    MANUAL_CALCULATE                                    = 130440,
    SET_AUTO_CALCULATE                                  = 130441,
    SAVE_BEAM_TEMPLATE                                  = 130442,
    DELETE_BEAM_TEMPLATE                                = 130443,
    UPDATE_BEAMTEMPLATE_PREVIEW                         = 130444,
    CREATE_BEAMS_FROM_TEMPLATE                          = 130445,
    RESET_DRR_WINDOWING                                 = 130446,
    CREATE_OPTGOAL                                      = 130447,
    UPDATE_OPTGOAL                                      = 130448,
    DELETE_OPTGOAL                                      = 130449,
    POI_CREATE_PLANNING                                 = 130450,
    POI_EDIT_2D_PLANNING                                = 130451,
    POI_UPDATE_ATTRIBUTE_PLANNING                       = 130452,
    POI_JUMP_TO_PLANNING                                = 130453,
    POI_DELETE_PLANNING                                 = 130454,
    ADD_VOI_ADVANCED_PLANNING                           = 130455,
    ADD_VOI_AUTO_PLANNING                               = 130456,
    DELETE_VOI_IN_PLANNING                             = 130457,
    SHADEDSURFACE_UPDATE_LIGHTSETTING                   = 130458,
    POI_CREATE_3DPOINT                                  = 130459,
    VOI_DOSE_VOLUME                                     = 130460,

    //for Evaluation 130601~130800
    CREATE_VIEW_MODULE_EV                               = 130601,
    SHOW_DVH_EV                                         = 130602,
    CHOOSE_EV1                                          = 130603,
    CHOOSE_EV2                                          = 130604,
    EVALUATION_MERGE                                    = 130605,
    EVALUATION_COMPARE                                  = 130606,
    EVALUATION_START_SIMULATOR                          = 130607,
    EVALUATION_APPROVE_PLAN                             = 130608,
    EVALUATION_CHECK_DATA                               = 130609,
    EVALUATION_APPROVE_NORMGROUP                        = 130610,
    EVALUATION_CREATE_MERGED_PLAN                       = 130611,
    EVALUATION_REMOVE_ORIGINAL_ORDER                    = 130612,

    // For EasyPlan 130801~131000
    CREATE_VIEW_MODULE_EASYPLAN                         = 130801,
    EASYPLAN_SET_ISOCENTER                              = 130802,
    EASYPLAN_LOAD_DATA                                  = 130803,
    EASYPLAN_LOAD_IMAGE                                 = 130804,
    EASYPLAN_ADD_PLAN                                   = 130805,
    EASYPLAN_SEND_PLAN_INFO                             = 130806,
    EASYPLAN_CALCULATE_DOSE                             = 130807,
    EASYPLAN_ADD_BEAM                                   = 130808,
    EASYPLAN_UPDATE_BEAMINFO                            = 130809,
    EASYPLAN_MLC_SMARTCONTOUR                           = 130810,
    EASYPLAN_MLC_RECTANGLE                              = 130811,
    EASYPLAN_MLC_CIRCLE                                 = 130812,
    EASYPLAN_MLC_NUDGE                                  = 130813,
    EASYPLAN_RESET_MLC                                  = 130814,
    EASYPLAN_WINDOWING                                  = 130815,
    EASYPLAN_SETPAN                                     = 130816,
    EASYPLAN_MEASUREDISTANCE                            = 130817,
    EASYPLAN_MEASUREANGLE                               = 130818,
    EASYPLAN_SETZOOM                                    = 130819,
    EASYPLAN_APPROVE_CMD                                = 130820,
    EASYPLAN_DELETE_PLAN                                = 130821,
    EASYPLAN_DELETE_BEAM                                = 130822,
    EASYPLAN_CHANGEBEAM_CMD                             = 130823,
    EASYPLAN_SETROTATION                                = 130824,
    EASYPLAN_DELETE_IMAGE                               = 130825,
    EASYPLAN_SETINVERSE                                 = 130826,
    EASYPLAN_SETRESETIMAGE                              = 130827,
    EASYPLAN_SAVE_PLAN                                  = 130828,
    EASYPLAN_SET_APERTURE_BLOCK                         = 130829,
    EASYPLAN_SET_SHIELD_BLOCK                           = 130830,
    EASYPLAN_SET_APERTURE_MLC                           = 130831,
    EASYPLAN_RECEIVE_IGRT_IMAGE                         = 130832,
    EASYPLAN_IGRT_IMAGE_POPWINDOW                       = 130833,
    EASYPLAN_CHANGEPLAN_CMD                             = 130834,
    EASYPLAN_DRAGMLC_CMD                                = 130835,
	EASYPLAN_MODIFY_BEAM                                = 130836,
    EASYPLAN_SEND_POI_INFO                              = 130837,
    EASYPLAN_DELETE_POI                                 = 130838,
    // For PlanQA 131001~131200
    CREATE_VIEW_MODULE_PLANQA                           = 131001,
    LOADIMAGE_PLANQA                                    = 131002,
    DELETE_IMAGE_PLANQA                                 = 131003,
    DELETE_PLAN_QA                                      = 131004,
    ADD_POI_QA                                          = 131005,
    ADD_VOI_QA                                          = 131006,
    ADD_BEAM_QA                                         = 131007,
    ADD_NORMGROUP_QA                                    = 131008,
    ADD_EMPTY_QA_PLAN                                   = 131009, // only plan
    ADD_QA_PLAN                                         = 131010, // include normgroups and beams
    UPDATE_GRIDSIZE_QA                                  = 131011,
    UPDATE_GRIDBOUNDARY_QA                              = 131012,
    SMART_CONTOUR_QA                                    = 131013,
    NUDGE_QA                                            = 131014,
    PLAN_QA_STARTUP                                     = 131015,
    VOI_POI_DELETE_QA                                   = 131016,
    PLAN_QA_CREATE_PHANTOM                              = 131017,
    PLAN_QA_ADDDOSELINE_PHANTOM                         = 131018,
    PLAN_QA_UPDATEDOSELINE_PHANTOM                      = 131019,
    PLAN_QA_UPDATEDOSELINECOMMON_PHANTOM                = 131020,
    PLAN_QA_PLANQADELETE_PHANTOM                        = 131021,
    AUTO_ADD_VOI_QA                                     = 131022,
    POI_CREATE_QA                                       = 131023,
    POI_EDIT_2D_QA                                      = 131024,
    POI_UPDATE_ATTRIBUTE_QA                             = 131025,
    POI_JUMP_TO_QA                                      = 131026,
    POI_DELETE_QA                                       = 131027,
    EXPORT_SLICE_DOSE_QA                                = 131028,
    POI_CREATE_PHANTOM                                  = 131029,

    // For Admin 131201~131400
    LOAD_IMAGE_PHANTOM                                  = 131201,
    CREATE_VIEW_MODULE_ADMIN                            = 131202,
    ADD_PHANTOM_VOI                                     = 131203,
    SMART_CONTOUR_PHANTOM                               = 131204,
    NUDGE_PHANTOM                                       = 131205,
    ADD_SYSTEM_CT2DENSITY_TABLE                         = 131206,
    UPDATE_SYSTEM_CT2DENSITY_TABLE                      = 131207,
    REMOVE_SYSTEM_CT2DENSITY_TABLE                      = 131208,
    PHANTOM_CREATE                                      = 131209,
    PHANTOM_DELETE                                      = 131210,
    PHANTOM_VOI_CREATE                                  = 131211,
    PHANTOM_VOI_AUTO_CREATE                             = 131212,
    PHANTOM_VOI_DELETE                                  = 131213,

    // For Extend 131401~132000
    DEV_PRINTDOSEGRIDINFO                               = 131401, // Dev Testing
    LOAD_COMMONREPORTDATA                               = 131402,
    REQUEST_PLANREPORT                                  = 131403,
	REQUEST_DVHREPORT									= 131404,

    // For Gallery (Use TMS CommandID)
    // FE --> BE : 121001~122000
    CREATE_VIEW_MODULE_GALLERY                  = 121001, 
    LOAD_PATIENT_GALLERY                        = 121002,
    LOAD_SERIES_GALLERY                         = 121003,
    MPR_PAGE_TURN_GALLERY                       = 121004,
    MPR_PAN_GALLERY                             = 121005,
    MPR_ZOOM_GALLERY                            = 121006,
    MPR_WINDOWING_GALLERY                       = 121007,
    MOUSE_POSITION_CHANGE_GALLERY               = 121008,
    MOVE_CROSSHAIR_GALLERY                      = 121009,
    CROSSHAIR_MODE_GALLERY                      = 121010,
    MPR_ROTATE_GALLERY                          = 121011,
    MEASUREANGLE_GALLERY                        = 121012,
    MEASUREDISTANCE_GALLERY                     = 121013,
    EDIT_COURSE_GALLERY                         = 121014,
    RELOAD_PATIENT_GALLERY                      = 121015,
    DELETE_SERIES_GALLERY                       = 121016,
    IMAGETEXT_VISIBLE_GALLERY                   = 121017,
    EXPAND_SERIES_GALLERY                       = 121018, 
    VR_ROTATE_GALLERY                           = 121019,
    GET_SLICEINFO_GALLERY                       = 121020,
    DELETE_CURRENTSLICE_GALLERY                 = 121021, // Delete in Client
    SAVE_SERIES_GALLERY                         = 121022, // TODO
    LEAVING_MODULE_GALLERY                      = 121023,
    HITTEST_MEASURE_GALLERY                     = 121024,
    EDIT_MEASUREANGLE_GALLERY                   = 121025,
    EDIT_MEASUREDISTANCE_GALLERY                = 121026,
    TEXT_GALLERY                                = 121027,
    HITTEST_TEXT_GALLERY                        = 121028,
    EDIT_TEXT_GALLERY                           = 121029,
};

#define TPS_FE_NAME "TPSFE"

//TPS Command: 130001~132000
//TPS Event: 1300001~1320000
// BE --> FE
enum TpsBE2FECommand{
    BE2FE_COMMAND                                   = -1,

    SEND_DVH_COMMAND                                = 130001,
    SEND_PREVIEW_COMMAND                            = 130002,
    SEND_MESH_DATA                                  = 130003,
    SERVICE_READY                                   = 130004,
    EASYPLAN_OUTPUT_POI_INFO                        = 130005,
    EASYPLAN_SEND_MEASUREDISTANCE_COMMAND           = 130006,
    EASYPLAN_SEND_POINT_COMMAND                     = 130007,
    SEND_REGISTRATION_FEEDBACK_COMMAND              = 130008,
    SEND_ERRORCODE_COMMAND                          = 130009,
    UPDATE_PROGRESS                                 = 130010,
    LOAD_SUMMARY_TO_FE                              = 130011,
    ADD_POI_TO_FE                                   = 130012,
    UPDATE_POI_TO_FE                                = 130013,
    UPDATE_VOI_TO_FE                                = 130014,
    UPDATE_OPTIMIZATION_RESULT                      = 130015,
    SET_CURRENT_SERIES_TO_FE                        = 130016,
    ADD_VOI_TO_FE                                   = 130017,
    UPDATE_BEAM_TO_FE                               = 130018,
    UPDATE_NORMGROUP_TO_FE                          = 130019,
    UPDATE_PLAN_TO_FE                               = 130020,
    EASYPLAN_OUTPUT_BEAMS_MU_INFO                   = 130021,
    MOVIE_PROGRESS_TO_FE                            = 130022,
    MOVIE4D_PROGRESS_TO_FE                          = 130023,
    VOI_DOSE_VOLUME_TO_FE                           = 130024,
    REPORT_UNDO_REDO_LIST_SIZE                      = 130025,
};

#endif //TPS_FW_COMMANDIDS_H_
